print("Mani")
print("i am mani thapa")
print("i am new lernner of programing language")
print("i would like to be a programmer in future")
print("this is my first class today")
print("i install vs code and python")
print("how can i run pythan")
print("first go to file and enter open file")
print("print write inside small braket and double comma")
print("write what would you like to print")

